default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: grddron1995

development:
  <<: *default
  database: todo_dev

test:
  <<: *default
  database: todo_test

production:
  <<: *default
database: todo_prod